[package]
name = "twitch_api2"
version = "0.6.0-rc.3"
authors = ["Emil Gardström <emil.gardstrom@gmail.com>"]
edition = "2018"
repository = "https://github.com/Emilgardis/twitch_api2"
license = "MIT OR Apache-2.0"
description = "Library for talking with the new Twitch API aka. \"Helix\", TMI and more!"
keywords = ["oauth", "twitch", "async", "asynchronous", "api"]
documentation = "https://docs.rs/twitch_api2/0.6.0-rc.3"
readme = "README.md"
resolver = "2"

[dependencies]
thiserror = "1.0.26"
displaydoc = "0.2.3"
http = "0.2.4"
typed-builder = { version = "0.9.0", optional = true }
url = "2.2.2"
once_cell = "1.8.0"
twitch_oauth2 = { version = "0.6.1", optional = true, path = "twitch_oauth2/" }
serde = { version = "1.0.127", features = ["derive"] }
serde_derive = "1.0.127"
serde_path_to_error = { version = "0.1.4", optional = true }
async-trait = { version = "0.1.51", optional = true }
serde_json = { version = "1.0.66", optional = true }
serde_repr = "0.1.7"
serde_ignored = { version = "0.1.2", optional = true }
tracing = { version = "0.1.26", optional = true }
ureq = { version = "2.4.0", optional = true, default-features = false, features = [
    "tls",
] }
reqwest = { version = "0.11.4", optional = true, default-features = false }
surf = { version = "2.2.0", optional = true, default-features = false }
http-types = { version = "2.12.0", optional = true, features = [
    "hyperium_http",
] }
sha2 = { version = "0.9.5", optional = true }
crypto_hmac = { package = "hmac", version = "0.11.0", optional = true }
aliri_braid = "0.1.9"
futures = { version = "0.3.16", optional = true }
time = { version = "0.3.4", optional = true, default-features = false, features = [
    "parsing",
    "formatting",
] }
hyper = { version = "0.14.18", optional = true }

[features]
default = []

client = ["twitch_oauth2", "dep:futures", "dep:hyper"]

unsupported = ["serde_json?/raw_value"]
deny_unknown_fields = []
trace_unknown_fields = ["dep:serde_ignored", "tracing"]

serde_json = ["dep:serde_json", "dep:serde_path_to_error"]
helix = ["dep:async-trait", "serde_json", "dep:typed-builder", "dep:hyper"]

tmi = ["serde_json", "dep:serde_path_to_error", "dep:hyper"]

surf = [
    "dep:surf",
    "dep:http-types",
    "client",
    "twitch_oauth2/surf_client",
    "hyper?/stream",
]

ureq = ["dep:ureq", "client"]

reqwest = ["dep:reqwest", "client", "twitch_oauth2/reqwest_client"]


pubsub = ["serde_json"]

eventsub = ["serde_json", "dep:typed-builder"]

hmac = ["dep:crypto_hmac", "dep:sha2"]

mock_api = []

all = [
    "tmi",
    "helix",
    "client",
    "pubsub",
    "eventsub",
    "hmac",
    "twitch_oauth2",
    "tracing",
    "time",
]

_all = [
    "all",
    "surf",
    "reqwest",
    "ureq",
    "twitch_oauth2/surf_client_curl",
    "twitch_oauth2/reqwest_client",
    "mock_api",
]

[dev-dependencies]
tokio = { version = "1.10.0", features = ["rt-multi-thread", "macros"] }
dotenv = "0.15.0"
futures = "0.3.16"
serde_cbor = "0.11.2"
serde_json = "1.0.66"
surf = "2.2.0"
reqwest = "0.11.4"
hyper = "0.14.18"


[build-dependencies]
version_check = "0.9.3"


[[example]]
name = "automod_check"
path = "examples/automod_check.rs"
required-features = ["surf_client", "helix"]

[[example]]
name = "get_channel_status"
path = "examples/get_channel_status.rs"
required-features = ["reqwest_client", "helix"]

[[example]]
name = "get_moderation"
path = "examples/get_moderation.rs"
required-features = ["surf_client", "helix"]

[[example]]
name = "get_streams_and_chatters"
path = "examples/get_streams_and_chatters.rs"
required-features = ["surf_client", "helix", "tmi"]

[[example]]
name = "modify_channel"
path = "examples/modify_channel.rs"

required-features = ["surf_client", "helix"]
[[example]]
name = "client"
path = "examples/client.rs"
required-features = ["reqwest_client", "helix"]

[[example]]
name = "channel_information"
path = "examples/channel_information.rs"
required-features = ["reqwest_client", "helix"]

[[example]]
name = "channel_information_custom"
path = "examples/channel_information_custom.rs"
required-features = ["reqwest_client", "helix", "unsupported"]

[[example]]
name = "followed_streams"
path = "examples/followed_streams.rs"
required-features = ["reqwest_client", "helix"]

[[example]]
name = "mock_api"
path = "examples/mock_api.rs"
required-features = [
    "reqwest_client",
    "helix",
    "mock_api",
    "twitch_oauth2/mock_api",
]

[package.metadata.docs.rs]
features = ["all", "unsupported", "_all"]
rustc-args = ["--cfg", "nightly"]
